language: node_js
node_js:
  - 14
cache:
  directories:
    - '$HOME/.npm'
install:
  - cd frontend
  - npm i
  - cd ../server
  - npm i
script:
  - npm run lint
  - cd ../frontend
  - npm run lint
  - npm run build
